# .goreleaser.yml
# Build customization

project_name: go-gocd

builds:
  - binary: gocd
    main: ./cli/*.go
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64

archive:
  name_template: "gocd-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
  format_overrides:
    - goos: windows
      format: zip
    - goos: darwin
      format: zip
  files:
    - LICENSE
    - README.md
    - CHANGELOG.md
fpm:
  homepage: https://github.com/drewsonne/gocdsdk
  maintainer: Drew J. Sonne <drew.sonne@gmail.com>
  license: LGPLv3
  formats:
    - deb
    - rpm

brew:
  github:
    owner: drewsonne
    name: homebrew-devops
  homepage: https://github.com/drewsonne/gocdsdk
  test: |
    system "#{bin}/gocd --version"
