language: go
go:
  - 1.8.x
  - 1.9.x
  - 1.10.x

env:
 - CODECLIMATE_API_HOST=https://codebeat.co/webhooks/code_coverage


addons:
  apt:
    packages:
    - rpm

matrix:
  fast_finish: true

before_install:
  - pip install codecov
  - make before_install

script:
  - go generate -x $(glide novendor) && git diff --exit-code; code=$?; git checkout -- .; (exit	$code)
  - make test

after_success:
  - codecov
  - go get github.com/goreleaser/goreleaser
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage.out

deploy:
  - provider: script
    skip_cleanup: true
    script: make deploy_on_tag
    on:
      tags: true
      condition: $TRAVIS_GO_VERSION =~ ^1\.10(\.[0-9]+)?$
  - provider: script
    skip_cleanup: true
    script: make deploy_on_develop
    on:
      branch: develop
      condition: $TRAVIS_GO_VERSION =~ ^1\.10(\.[0-9]+)?$
