language: go
go:
 - 1.7.x
 - 1.8.x
 - release
 - tip

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/modocache/gover

script:
  - go test -v ./... -race -coverprofile=coverprofile.out -covermode=atomic
  - gover . coverprofile.out

after_success:
  # Send coverage reports to Codecov
  - cat coverprofile.out
  - bash <(curl -s https://codecov.io/bash) -f coverprofile.out