language: go
go:
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - release
  - tip

addons:
  apt:
    packages:
    - rpm

matrix:
  allow_failures:
    - go: 1.9.x
    - go: release
    - go: tip
  fast_finish: true

#cache:
#  directories:
#    - $GOPATH/src
#    - $GOPATH/pkg

jobs:
  include:
    - stage:

before_install:
  - make before_install

script:
  - go generate -x ./... && git diff --exit-code; code=$?; git checkout -- .; (exit	$code)
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - go get github.com/goreleaser/goreleaser

deploy:
  - provider: script
    skip_cleanup: true
    script: make deploy_on_tag
    on:
      tags: true
      condition: $TRAVIS_GO_VERSION =~ ^1\.8\.[0-9]+$
  - provider: script
    skip_cleanup: true
    script: make deploy_on_develop
    on:
      branch: develop
      condition: $TRAVIS_GO_VERSION =~ ^1\.8\.[0-9]+$
