language: go
go:
 - 1.7.x
 - 1.8.x
 - release
 - tip

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/modocache/gover

script:
  - go test -v ./...
#  - go test -v ./... -coverprofile=cover.out
  - go list -f '{{if len .TestGoFiles}}"go test -coverprofile={{.Dir}}/.coverprofile {{.ImportPath}}"{{end}}' ./... | xargs -i sh -c {}
  - gover . coverprofile.txt

after_success:
  # Send coverage reports to Codecov
  - bash < (curl -s https://codecov.io/bash) -f coverprofile.txt