[[constraint]]
  branch = "master"
  name = "github.com/sirupsen/logrus"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  name = "gopkg.in/AlecAivazis/survey.v1"
  version = "1.4.1"

[prune]
  go-tests = true
  unused-packages = true
