# .goreleaser.yml
# Build customization
builds:
  - binary: gocd
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
fpm:
  homepage: https://github.com/drewsonne/gocdsdk
  maintainer: Drew J. Sonne <drew.sonne@gmail.com>
  license: LGPLv3
  formats:
    - deb
    - rpm
