# .goreleaser.yml
# Build customization
builds:
  - binary: gocd
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64

archive:
  name_template: "gocd-{{ .Version }}-{{ .Os }}-{{ .Arch }}"

fpm:
  homepage: https://github.com/drewsonne/gocdsdk
  maintainer: Drew J. Sonne <drew.sonne@gmail.com>
  license: LGPLv3
  formats:
    - deb
    - rpm

brew:
  github.com:
    owner: drewsonne
    name: homebrew-devops
    homepage: https://github.com/drewsonne/gocdsdk
    test: |
      system "#{bin}/gocd --version"
